### ISSUE TITLE
Heartstone failing to function properly

### ISSUE THREAD

**Issue by Typhonidite** [MehVahdJukaar/heartstone#1]
https://mclo.gs/40UVn7e#L1952

I'm not sure what the mod could be conflicting with... I'm not knowledgeable enough to decipher this log. Optifine? Some other mod?

**Comment by MehVahdJukaar** [comment]
well thats embarassing. seems like mod was bugged in multiplayer since last update. Surprised this got reported so late considering the mod only works there
