### ISSUE TITLE
"The specified mixin 'net.mehvahdjukaar.heartstone.mixins.MapItemSavedDataMixin' was not found"

### ISSUE THREAD

**Issue by Typhonidite** [MehVahdJukaar/heartstone#10]
???

[latest.log](https://github.com/MehVahdJukaar/heartstone/files/13256195/latest.log)

Not, uh, too sure what's happening here. Latest versions of Supp and Moon (2.6.19, 2.8.56, respectively).
Maybe caused by the recent map api changes? I don't _think_ it's a mod conflict, or something on my end... then again, I definitely could have missed something in the log.

**Comment by MehVahdJukaar** [comment]
You sure heartdtones is latest version?

**Comment by Typhonidite** [comment]
...after checking Heartstone's Curseforge page just now instead of the Modrinth page... no, no I am not sure.
